//HintName: NsisPluginInitializer.g.cs
// <auto-generated/>

namespace NsisPlugin.AutoGenerated
{
    internal static class NsisPluginInitializer
    {
        private static byte _moduleAnchor;

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            const int GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS = 0x00000004;
            if (GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, ref _moduleAnchor, out global::System.IntPtr hModule)) global::NsisPlugin.NsPlugin.ModuleHandle = hModule;

#if NSIS_UNICODE
            global::NsisPlugin.NsPluginEnc.UseUnicode = true;
#else
            global::NsisPlugin.NsPluginEnc.UseUnicode = false;
#endif

            [global::System.Runtime.InteropServices.DllImportAttribute("kernel32.dll")]
            static extern bool GetModuleHandleEx(int dwFlags, ref byte lpModuleName, out global::System.IntPtr phModule);
        }
    }
}
