//HintName: NsisPluginTest.AA.EntryPointCases.NsisExports.g.cs
// <auto-generated />

namespace NsisPluginTest
{
    public static class AA_EntryPointCases_NsisExports
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "DefaultEntry", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void DefaultEntry_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int? val)) throw new global::System.Exception("Failed to get 'val'(int?) from the stack");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out string a)) throw new global::System.Exception("Failed to get 'a'(string) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.DefaultEntry(val, a);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in DefaultEntry: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "My_FormatEntry_Entry", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void My_FormatEntry_Entry_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Ansi);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int value)) throw new global::System.Exception("Failed to get 'value'(int) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.FormatEntry(value);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in My_FormatEntry_Entry: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "LiteralEntry", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void LiteralEntry_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int value)) throw new global::System.Exception("Failed to get 'value'(int) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.LiteralEntry(value);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in LiteralEntry: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "BadFormatEntry", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void BadFormatEntry_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int value)) throw new global::System.Exception("Failed to get 'value'(int) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.BadFormatEntry(value);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in BadFormatEntry: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void _Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int value)) throw new global::System.Exception("Failed to get 'value'(int) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.EmptyEntry(value);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in : {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "   ", CallConvs = new Type[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void    _Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int value)) throw new global::System.Exception("Failed to get 'value'(int) from the stack");

                var result = global::NsisPluginTest.AA.EntryPointCases.WhitespaceEntry(value);
                global::NsisPlugin.NsPluginExtensions.Push(global::NsisPlugin.NsPlugin.StackTop, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in    : {ex}");
            }
        }
    }
}
