//HintName: Demo.ExportMethods.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class ExportMethods_NsisExports
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "demo_Add", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void demo_Add_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Get(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.Variables.Inst1, out int fromVar)) throw new global::System.Exception("Failed to get 'fromVar'(int) from the variable");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int fromStack)) throw new global::System.Exception("Failed to get 'fromStack'(int) from the stack");

                var result = global::Demo.ExportMethods.Add(fromVar, fromStack, global::NsisPlugin.NsPlugin.StackTop, global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsPlugin.ExtraParameters);
                global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.Variables.Inst0, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in demo_Add: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Ping", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Ping_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                global::Demo.ExportMethods.Ping();
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in Ping: {ex}");
            }
        }
    }
}
