//HintName: NsisPluginTest_BindingCases.NsisExports.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace NsisPluginTest
{
    public static class BindingCasesNsisExports
    {
        [UnmanagedCallersOnly(EntryPoint = "StackReturn", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Add_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? left)) throw new Exception("Failed to pop left");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? right)) throw new Exception("Failed to pop right");

                global::System.Int32 result = global::NsisPluginTest.BindingCases.Add(left.Value, right.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Add_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "Bind_Combine", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Combine_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.Variables.Get(global::NsisPlugin.NsVariable.Inst1, out global::System.Int32? count)) throw new Exception("Failed to get count");
                if (!NsPlugin.StackTop.Pop(out global::System.String? name)) throw new Exception("Failed to pop name");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? optional)) throw new Exception("Failed to pop optional");

                global::System.String result = global::NsisPluginTest.BindingCases.Combine(count.Value, name!, optional, NsPlugin.Variables, NsPlugin.StackTop, NsPlugin.ExtraParameters);

                NsPlugin.Variables.Set(global::NsisPlugin.NsVariable.InstR0, result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Combine_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "VoidCase", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Do_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.Variables.Get(global::NsisPlugin.NsVariable.Inst2, out global::System.String? value)) throw new Exception("Failed to get value");

                global::NsisPluginTest.BindingCases.Do(value!);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Do_Gen: {ex}");
            }
        }
    }
}
