//HintName: NsisPluginTest_EntryPointCases.NsisExports.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace NsisPluginTest
{
    public static class EntryPointCasesNsisExports
    {
        [UnmanagedCallersOnly(EntryPoint = "Bad {0", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void BadFormatEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.BadFormatEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in BadFormatEntry_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "DefaultEntry", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void DefaultEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.DefaultEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in DefaultEntry_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "EmptyEntry", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void EmptyEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.EmptyEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in EmptyEntry_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "My_FormatEntry_Entry", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void FormatEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Ansi);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.FormatEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in FormatEntry_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "LiteralEntry", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void LiteralEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.LiteralEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in LiteralEntry_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "WhitespaceEntry", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void WhitespaceEntry_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.EntryPointCases.WhitespaceEntry(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in WhitespaceEntry_Gen: {ex}");
            }
        }
    }
}
