//HintName: NsisPluginTest_NsisPluginSpecials.NsisExports.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace NsisPluginTest
{
    public static class NsisPluginSpecialsNsisExports
    {
        [UnmanagedCallersOnly(EntryPoint = "SetVar", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void SetVar_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.Variables.Get(global::NsisPlugin.NsVariable.Inst2, out global::System.String? value)) throw new Exception("Failed to get value");

                global::NsisPluginTest.NsisPluginSpecials.SetVar(value!);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in SetVar_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "Sum_Sum", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Sum_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.Variables.Get(global::NsisPlugin.NsVariable.Inst1, out global::System.Int32? v1)) throw new Exception("Failed to get v1");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v2)) throw new Exception("Failed to pop v2");

                global::System.Int32 result = global::NsisPluginTest.NsisPluginSpecials.Sum(v1.Value, v2.Value, NsPlugin.Variables, NsPlugin.StackTop, NsPlugin.ExtraParameters);

                NsPlugin.Variables.Set(global::NsisPlugin.NsVariable.InstR0, result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Sum_Gen: {ex}");
            }
        }
    }
}
