//HintName: NsisPluginInitializer.g.cs
// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace AutoGenerated
{
    internal static class NsisPluginInitializer
    {
        [ModuleInitializerAttribute]
        internal static void Initialize()
        {
            string currentModuleName = $"{Assembly.GetExecutingAssembly().GetName().Name}.dll";
            NsPlugin.ModuleHandle = GetModuleHandle(currentModuleName);

#if NSIS_UNICODE
            NsPluginEnc.IsGlobalUnicode = true;
#else
            NsPluginEnc.IsGlobalUnicode = false;
#endif

            [DllImport("kernel32.dll")]
            static extern IntPtr GetModuleHandle(string lpModuleName);
        }
    }
}
