//HintName: NsisPluginTest_NsisPluginTest.NsisExports.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace NsisPluginTest
{
    public static class NsisPluginTestNsisExports
    {
        [UnmanagedCallersOnly(EntryPoint = "AddU", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Add_AddU_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v1)) throw new Exception("Failed to pop v1");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v2)) throw new Exception("Failed to pop v2");

                global::System.Int32 result = global::NsisPluginTest.NsisPluginTest.Add(v1.Value, v2.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Add_AddU_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "AddA", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Add_AddA_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Ansi);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v1)) throw new Exception("Failed to pop v1");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v2)) throw new Exception("Failed to pop v2");

                global::System.Int32 result = global::NsisPluginTest.NsisPluginTest.Add(v1.Value, v2.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Add_AddA_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "AddUndefined", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Add_AddUndefined_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v1)) throw new Exception("Failed to pop v1");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v2)) throw new Exception("Failed to pop v2");

                global::System.Int32 result = global::NsisPluginTest.NsisPluginTest.Add(v1.Value, v2.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Add_AddUndefined_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "Add2", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Add2_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v1)) throw new Exception("Failed to pop v1");
                if (!NsPlugin.StackTop.Pop(out global::System.Int32? v2)) throw new Exception("Failed to pop v2");

                global::System.Threading.Tasks.Task<global::System.Int32> result = global::NsisPluginTest.NsisPluginTest.Add2(v1.Value, v2.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Add2_Gen: {ex}");
            }
        }
    }
}
