//HintName: NsisPluginInitializer.g.cs
// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace AutoGenerated
{
    internal static class NsisPluginInitializer
    {
        private static byte _moduleAnchor;

        [ModuleInitializerAttribute]
        internal static void Initialize()
        {
            const int GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS = 0x00000004;
            if (GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, ref _moduleAnchor, out IntPtr hModule)) NsPlugin.ModuleHandle = hModule;

#if NSIS_UNICODE
            NsPluginEnc.UseUnicode = true;
#else
            NsPluginEnc.UseUnicode = false;
#endif

            [DllImport("kernel32.dll")]
            static extern bool GetModuleHandleEx(int dwFlags, ref byte lpModuleName, out IntPtr phModule);
        }
    }
}
