//HintName: NsisPluginTest_MultiAttributeCases.NsisExports.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using NsisPlugin;

namespace NsisPluginTest
{
    public static class MultiAttributeCasesNsisExports
    {
        [UnmanagedCallersOnly(EntryPoint = "Dup", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Multi_Dup_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.MultiAttributeCases.Multi(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Multi_Dup_Gen: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "Dup", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Multi_Dup_Gen_1(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.MultiAttributeCases.Multi(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Multi_Dup_Gen_1: {ex}");
            }
        }

        [UnmanagedCallersOnly(EntryPoint = "Fmt_Multi", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static void Multi_Fmt_Multi_Gen(IntPtr hwndParent, int string_size, IntPtr variables, IntPtr stacktop, IntPtr extra)
        {
            try
            {
                using IDisposable _ = NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!NsPlugin.StackTop.Pop(out global::System.Int32? value)) throw new Exception("Failed to pop value");

                global::System.Int32 result = global::NsisPluginTest.MultiAttributeCases.Multi(value.Value);

                NsPlugin.StackTop.Push(result);
            }
            catch (Exception ex)
            {
                NsPlugin.StackTop.Push($"Exception in Multi_Fmt_Multi_Gen: {ex}");
            }
        }
    }
}
