name: 错误报告
labels: ["bug"]
description: 提交一个错误报告
body:
  - type: textarea
    id: description
    attributes:
      label: 错误描述
      description: 一个清晰简洁的描述，说明这个错误是什么。
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: 复现该错误的步骤。
      value: |
        1.
        2.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      description: 你期望的正确表现是什么？

  - type: textarea
    id: env-info
    attributes:
      label: 环境信息
      description: 操作系统信息、.NET 信息、Nsis 信息、NsisPlugin 信息等。
      placeholder: |
        - 操作系统 : Windows 10 x64 22H2(Build 19045.2965)
        - .NET : .NET 8.0.0
        - Nsis : 3.11
        - NsisPlugin : 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 额外信息
      description: 如有截图、日志或错误信息，请在此处粘贴。
      placeholder: 可拖拽图片或粘贴错误日志。

