//HintName: Outer.Inner.NsisExports.g.cs
// <auto-generated />

public static class Outer_Inner_NsisExports
{
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Do", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
    public static void Do_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
    {
        using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.NsEncoding.Undefined);
        global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);
        try
        {
            global::Outer.Inner.Work();
        }
        catch (global::System.Exception ex)
        {
            global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in Do: {ex}");
        }
    }
}
