//HintName: Demo.NullFormatCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class NullFormatCases_NsisExports
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Work", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Work_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.NsEncoding.Undefined);
            global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);
            try
            {
                global::Demo.NullFormatCases.Work();
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in Work: {ex}");
            }
        }
    }
}
