//HintName: Demo.MixedEligibilityCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class MixedEligibilityCases_NsisExports
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "ok", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void ok_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.NsEncoding.Undefined);
            global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);
            try
            {
                global::Demo.MixedEligibilityCases.Visible();
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in ok: {ex}");
            }
        }
    }
}
