//HintName: Demo.BasicCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class BasicCases_NsisExports
    {
        // Call the Ping method
        private static void Ping_Call()
        {
            global::Demo.BasicCases.Ping();
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Ping", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Ping_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "Ping", Ping_Call);
        }
    }
}
