//HintName: Demo.FirstType.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class FirstType_NsisExports
    {
        // Call the First method
        private static void First_Call()
        {
            global::Demo.FirstType.First();
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Dup", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Dup_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "Dup", First_Call);
        }
    }
}
