//HintName: Demo.ConflictCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class ConflictCases_NsisExports
    {
        // Call the Work method
        private static void Work_Call()
        {
            global::Demo.ConflictCases.Work();
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "A", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void A_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "A", Work_Call);
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "B", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void B_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "B", Work_Call);
        }
    }
}
