//HintName: NsisPlugin.EntryInit.g.cs
// <auto-generated />

namespace NsisPlugin.AutoGenerated
{
    internal static class __NsisPluginExportEntryInit
    {
        public static void Invoke(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra, global::NsisPlugin.NsEncoding encoding, string entryPoint, global::System.Action action)
        {
            using var _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(encoding);
            global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);
            try
            {
                action();
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in {entryPoint}: {ex}");
            }
        }
    }
}
