//HintName: Outer.Inner.NsisExports.g.cs
// <auto-generated />

public static class Outer_Inner_NsisExports
{
    // Call the Work method
    private static void Work_Call()
    {
        global::Outer.Inner.Work();
    }
    [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Do", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
    public static void Do_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
    {
        global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "Do", Work_Call);
    }
}
