//HintName: Demo.NullFormatCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class NullFormatCases_NsisExports
    {
        // Call the Work method
        private static void Work_Call()
        {
            global::Demo.NullFormatCases.Work();
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Work", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Work_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "Work", Work_Call);
        }
    }
}
