//HintName: Demo.MixedEligibilityCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class MixedEligibilityCases_NsisExports
    {
        // Call the Visible method
        private static void Visible_Call()
        {
            global::Demo.MixedEligibilityCases.Visible();
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "ok", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void ok_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "ok", Visible_Call);
        }
    }
}
