//HintName: Demo.FullFlowCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class FullFlowCases_NsisExports
    {
        // Call the Add method
        private static void Add_Call()
        {
            if (!global::NsisPlugin.NsPluginExtensions.Get(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst2, out int fromVar_p0)) throw new global::System.Exception("Failed to get 'fromVar'(int) from the variable");
            if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int fromStack_p1)) throw new global::System.Exception("Failed to get 'fromStack'(int) from the stack");

            var result = global::Demo.FullFlowCases.Add(fromVar_p0, fromStack_p1, global::NsisPlugin.NsPlugin.StackTop, global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsPlugin.ExtraParameters);
            global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst0, result);
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_Add", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_Add_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Undefined, "sum_Add", Add_Call);
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_AddA", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_AddA_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Ansi, "sum_AddA", Add_Call);
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_AddU", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_AddU_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Unicode, "sum_AddU", Add_Call);
        }

        // Call the Work method
        private static void Work_Call()
        {
            var result = global::Demo.FullFlowCases.Work(global::NsisPlugin.NsPlugin.StackTop, global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsPlugin.ExtraParameters);
            global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst0, result);
        }
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "Work", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Work_Entry(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            global::NsisPlugin.AutoGenerated.__NsisPluginExportEntryInit.Invoke(hwndParent, string_size, variables, stacktop, extra, global::NsisPlugin.NsEncoding.Ansi, "Work", Work_Call);
        }
    }
}
