//HintName: Demo.FullFlowCases.NsisExports.g.cs
// <auto-generated />

namespace Demo
{
    public static class FullFlowCases_NsisExports
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_Add", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_Add_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Undefined);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Get(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst2, out int fromVar)) throw new global::System.Exception("Failed to get 'fromVar'(int) from the variable");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int fromStack)) throw new global::System.Exception("Failed to get 'fromStack'(int) from the stack");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out global::NsisPlugin.Variables vars)) throw new global::System.Exception("Failed to get 'vars'(global::NsisPlugin.Variables) from the stack");

                var result = global::Demo.FullFlowCases.Add(fromVar, fromStack, global::NsisPlugin.NsPlugin.StackTop, vars, global::NsisPlugin.NsPlugin.ExtraParameters);
                global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst0, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in sum_Add: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_AddA", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_AddA_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Ansi);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Get(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst2, out int fromVar)) throw new global::System.Exception("Failed to get 'fromVar'(int) from the variable");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int fromStack)) throw new global::System.Exception("Failed to get 'fromStack'(int) from the stack");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out global::NsisPlugin.Variables vars)) throw new global::System.Exception("Failed to get 'vars'(global::NsisPlugin.Variables) from the stack");

                var result = global::Demo.FullFlowCases.Add(fromVar, fromStack, global::NsisPlugin.NsPlugin.StackTop, vars, global::NsisPlugin.NsPlugin.ExtraParameters);
                global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst0, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in sum_AddA: {ex}");
            }
        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "sum_AddU", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void sum_AddU_Gen(global::System.IntPtr hwndParent, int string_size, global::System.IntPtr variables, global::System.IntPtr stacktop, global::System.IntPtr extra)
        {
            try
            {
                using global::System.IDisposable _ = global::NsisPlugin.NsPluginEnc.CreateEncScope(global::NsisPlugin.Encodings.Unicode);
                global::NsisPlugin.NsPlugin.Init(hwndParent, string_size, variables, stacktop, extra);

                if (!global::NsisPlugin.NsPluginExtensions.Get(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst2, out int fromVar)) throw new global::System.Exception("Failed to get 'fromVar'(int) from the variable");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out int fromStack)) throw new global::System.Exception("Failed to get 'fromStack'(int) from the stack");
                if (!global::NsisPlugin.NsPluginExtensions.Pop(global::NsisPlugin.NsPlugin.StackTop, out global::NsisPlugin.Variables vars)) throw new global::System.Exception("Failed to get 'vars'(global::NsisPlugin.Variables) from the stack");

                var result = global::Demo.FullFlowCases.Add(fromVar, fromStack, global::NsisPlugin.NsPlugin.StackTop, vars, global::NsisPlugin.NsPlugin.ExtraParameters);
                global::NsisPlugin.NsPluginExtensions.Set(global::NsisPlugin.NsPlugin.Variables, global::NsisPlugin.NsVariable.Inst0, result);
            }
            catch (global::System.Exception ex)
            {
                global::NsisPlugin.NsPlugin.StackTop.Push($"Exception in sum_AddU: {ex}");
            }
        }
    }
}
